language: python
sudo: false
install: pip install tox coveralls
script: tox -e $TOX_ENV
after_success: coveralls
before_script:
    - cp t_overrides.travis.py t_overrides.py
    - psql -U postgres -c "DROP DATABASE IF EXISTS multigtfs"
    - psql -U postgres -c "CREATE DATABASE multigtfs"
    - psql -U postgres -d multigtfs -c "CREATE EXTENSION IF NOT EXISTS postgis; CREATE EXTENSION IF NOT EXISTS postgis_topology;"
matrix:
    include:
        - env: TOX_ENV=py27-django18-postgis
          python: "2.7"
        - env: TOX_ENV=py34-django18-postgis
          python: "3.4"
        - env: TOX_ENV=py27-django19-postgis
          python: "2.7"
        - env: TOX_ENV=py35-django19-postgis
          python: "3.5"
        - env: TOX_ENV=py27-django110-postgis
          python: "2.7"
        - env: TOX_ENV=py35-django110-postgis
          python: "3.5"
        - env: TOX_ENV=py27-django111-postgis
          python: "2.7"
        - env: TOX_ENV=py36-django111-postgis
          python: "3.6"
        - env: TOX_ENV=py35-django20-postgis
          python: "3.5"
        - env: TOX_ENV=py36-django20-postgis
          python: "3.6"
        - env: TOX_ENV=py35-django-master-postgis
          python: "3.5"
        - env: TOX_ENV=py36-django-master-postgis
          python: "3.6"
    allow_failures:
        # Django 2.0 is in beta
        - env: TOX_ENV=py35-django20-postgis
        - env: TOX_ENV=py36-django20-postgis
        # Django master is allowed to fail
        - env: TOX_ENV=py35-django-master-postgis
        - env: TOX_ENV=py36-django-master-postgis
